- hosts: minecraft-anarchy.org
  become: false
  vars:
    # As this is most likely the first time we connect, auto accept the ssh host key in this play only
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

    - name: install python using only a ssh command from localhost
      local_action: "shell ssh -o StrictHostKeyChecking=no root@{{ ansible_hostname }} 'apt-get -y install python'"
      become: false

    - name: debconf questions for unattended-upgrades
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        vtype: boolean
        value: true

    - name: install some basic packages
      apt:
        name: "{{ basic_packages }}"
        state: present
      with_items: ['python-dev', 'python-apt', 'unattended-upgrades', 'aptitude']
      loop_control:
        loop_var: basic_packages

    - name: apt-get upgrade
      apt:
        upgrade: false
        update_cache: false

    - name: set hostname via hostname module
      hostname:
        name: minecraft-anarchy.org

    - name: set hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 minecraft-anarchy minecraft-anarchy.org"
        state: present

    - name: set hostname in /etc/hostname
      copy:
        dest: /etc/hostname
        content: minecraft-anarchy.org
